In [18]:
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
import pickle
from skelm import ELMClassifier
from sklearn.metrics import accuracy_score, recall_score,confusion_matrix


In [23]:
import pickle
#Load the trained sgd model
svc_linear       = pickle.load(open('svc_linear.sav', 'rb'))
elm_classifier   = pickle.load(open('elm_classifier.sav', 'rb'))
mlp_classifier   = pickle.load(open('mlp_classifier.sav', 'rb'))
rf_bidirection   = pickle.load(open('rf_bidirection.sav', 'rb'))
rf_first_variable= pickle.load(open('rf_first_variable.sav', 'rb'))

data=pd.read_csv('Group_6_data_cleaned.csv')
df = data.drop(['Unnamed: 0'],axis=1)
x= df.drop(['Result'],axis=1)
y = df['Result']

# Oversampling and transform the dataset
import imblearn
from imblearn.over_sampling import SMOTE
oversample = SMOTE()
x,y= oversample.fit_resample(x, y)

#Extracts test set from the dataset
# keeping the random_state value same makes the function to split same rows into training and testing every time
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state=30)

In [4]:
from sklearn.metrics import accuracy_score,f1_score,recall_score,classification_report,confusion_matrix,roc_auc_score

## SVC Linear model Test Results

In [5]:
svc_linear.fit(x_train,y_train)
y_test_p = svc_linear.predict(x_test)
print("accuracy score is ",accuracy_score(y_test,y_test_p))
print("f1_score is ",f1_score(y_test,y_test_p,average='weighted'))
print("recall score is ",recall_score(y_test,y_test_p,average='weighted'))

accuracy score is  0.8033175355450237
f1_score is  0.8036686818486966
recall score is  0.8033175355450237


In [6]:
print(classification_report(y_test,y_test_p))

              precision    recall  f1-score   support

          -1       0.86      0.83      0.84       153
           0       0.81      0.83      0.82       149
           1       0.73      0.74      0.74       120

    accuracy                           0.80       422
   macro avg       0.80      0.80      0.80       422
weighted avg       0.80      0.80      0.80       422



In [7]:
print(confusion_matrix(y_test,y_test_p))

[[127  13  13]
 [  6 123  20]
 [ 15  16  89]]


# ELM Moodel Test Results

In [8]:
elm_classifier.fit(x_train,y_train)
y_test_p = elm_classifier.predict(x_test)
print("accuracy score is ",accuracy_score(y_test,y_test_p))
print("f1_score is ",f1_score(y_test,y_test_p,average='weighted'))
print("recall score is ",recall_score(y_test,y_test_p,average='weighted'))

accuracy score is  0.8554502369668247
f1_score is  0.8563159108044792
recall score is  0.8554502369668247


In [9]:
print(classification_report(y_test,y_test_p))

              precision    recall  f1-score   support

          -1       0.87      0.86      0.86       153
           0       0.91      0.84      0.87       149
           1       0.78      0.88      0.82       120

    accuracy                           0.86       422
   macro avg       0.85      0.86      0.85       422
weighted avg       0.86      0.86      0.86       422



In [10]:
print(confusion_matrix(y_test,y_test_p))

[[131   6  16]
 [ 10 125  14]
 [  9   6 105]]


# MLP Model Test Results

In [11]:
mlp_classifier.fit(x_train,y_train)
y_test_p = mlp_classifier.predict(x_test)
print("accuracy score is ",accuracy_score(y_test,y_test_p))
print("f1_score is ",f1_score(y_test,y_test_p,average='weighted'))
print("recall score is ",recall_score(y_test,y_test_p,average='weighted'))

accuracy score is  0.7914691943127962
f1_score is  0.7932227369855548
recall score is  0.7914691943127962


In [12]:
print(classification_report(y_test,y_test_p))

              precision    recall  f1-score   support

          -1       0.89      0.79      0.84       153
           0       0.79      0.81      0.80       149
           1       0.70      0.77      0.73       120

    accuracy                           0.79       422
   macro avg       0.79      0.79      0.79       422
weighted avg       0.80      0.79      0.79       422



In [13]:
print(confusion_matrix(y_test,y_test_p))

[[121  16  16]
 [  4 121  24]
 [ 11  17  92]]


# Best Model from Part 2 (Bi-Directional ): Random Forest


In [15]:
rf_bidirection.fit(x_train,y_train)
y_test_p = rf_bidirection.predict(x_test)
print("accuracy score is ",accuracy_score(y_test,y_test_p))
print("f1_score is ",f1_score(y_test,y_test_p,average='weighted'))
print("recall score is ",recall_score(y_test,y_test_p,average='weighted'))

accuracy score is  0.9289099526066351
f1_score is  0.9284551256082211
recall score is  0.9289099526066351


In [16]:
print(classification_report(y_test,y_test_p))

              precision    recall  f1-score   support

          -1       0.91      0.90      0.90       153
           0       0.97      1.00      0.99       149
           1       0.90      0.88      0.89       120

    accuracy                           0.93       422
   macro avg       0.93      0.93      0.93       422
weighted avg       0.93      0.93      0.93       422



In [17]:
print(confusion_matrix(y_test,y_test_p))

[[138   3  12]
 [  0 149   0]
 [ 14   1 105]]


# Best Model from Part 3(Bi-Directional ): ELM


In [19]:
# Define ELM classifier with default parameters
clf = ELMClassifier()
model_2 = ELMClassifier(n_neurons = 1000,ufunc = 'relu',alpha = 0.1)

In [20]:
model_2.fit(x_train,y_train)
elm_preds = model_2.predict(x_test)
print("accuracy score is ",accuracy_score(y_test,elm_preds))
print("f1_score is ",f1_score(y_test,elm_preds,average='weighted'))
print("recall score is ",recall_score(y_test,elm_preds,average='weighted'))

accuracy score is  0.9265402843601895
f1_score is  0.9257386735710097
recall score is  0.9265402843601895


In [21]:
print(classification_report(y_test,y_test_p))

              precision    recall  f1-score   support

          -1       0.91      0.90      0.90       153
           0       0.97      1.00      0.99       149
           1       0.90      0.88      0.89       120

    accuracy                           0.93       422
   macro avg       0.93      0.93      0.93       422
weighted avg       0.93      0.93      0.93       422



In [22]:
print(confusion_matrix(y_test,y_test_p))

[[138   3  12]
 [  0 149   0]
 [ 14   1 105]]


# Best Model from Part 2(first-variable-selection ): Random Forest


In [24]:
rf_first_variable.fit(x_train,y_train)
y_test_p = rf_first_variable.predict(x_test)
print("accuracy score is ",accuracy_score(y_test,y_test_p))
print("f1_score is ",f1_score(y_test,y_test_p,average='weighted'))
print("recall score is ",recall_score(y_test,y_test_p,average='weighted'))

accuracy score is  0.9265402843601895
f1_score is  0.9263737864495399
recall score is  0.9265402843601895


In [25]:
print(classification_report(y_test,y_test_p))

              precision    recall  f1-score   support

          -1       0.90      0.92      0.91       153
           0       0.97      0.97      0.97       149
           1       0.91      0.88      0.89       120

    accuracy                           0.93       422
   macro avg       0.93      0.92      0.92       422
weighted avg       0.93      0.93      0.93       422



In [26]:
print(confusion_matrix(y_test,y_test_p))

[[141   3   9]
 [  3 145   1]
 [ 13   2 105]]


# Best Model from Part 3(first-variable-selection ): ELM


In [28]:
model_2 = ELMClassifier(alpha=0.001, n_neurons=1000)
model_2.fit(x_train,y_train)

ELMClassifier(alpha=0.001, n_neurons=1000)

In [29]:
elm_preds = model_2.predict(x_test)
print("accuracy score is ",accuracy_score(y_test,elm_preds))
print("f1_score is ",f1_score(y_test,elm_preds,average='weighted'))
print("recall score is ",recall_score(y_test,elm_preds,average='weighted'))

accuracy score is  0.8412322274881516
f1_score is  0.8434340758134908
recall score is  0.8412322274881516
